  - name: Install ufw
    ansible.builtin.apt:
      name: ufw
  - name: Outgoing allow
    community.general.ufw:
      state: enabled
      direction: outgoing
      policy: allow

  - name: Incoming deny
    community.general.ufw:
      state: enabled
      direction: incoming
      policy: deny

  - name: Allow ssh
    community.general.ufw:
      rule: allow
      port: ssh
      proto: tcp
