  - name: Install ufw
    ansible.builtin.apt:
      name: ufw
  - name: Outgoing allow
    community.general.ufw:
      state: enabled
      direction: outgoing
      policy: allow

  - name: Incoming deny
    community.general.ufw:
      state: enabled
      direction: incoming
      policy: deny

  - name: Allow ssh
    community.general.ufw:
      rule: allow
      port: ssh
      proto: tcp
  
  - name: Allow Wireguard
    community.general.ufw:
      rule: allow
      port: '51820'
      proto: udp

  - name: Allow Wireguard-UI
    community.general.ufw:
      rule: allow
      port: '51821'
      proto: tcp

  - name: Allow code-server
    community.general.ufw:
      rule: allow
      port: '8443'
      proto: tcp
